name: Greeting  # Name of workflow
on : [push, workflow_dispatch]  # Trigger events
jobs:   # task to be perform
    test:   # what to run
        runs-on: ubuntu-latest  # run on which machine
        steps: 
            - name:  Get Code
              uses: actions/checkout@v5   # clone code at remote machine
              #run: |
              #echo "cloning repo."
              #echo "${{toJson(github)}}"
              #git clone https://github.com/aliahmadamin985/ci-cd.git

            - name: Install nodejs V20
              uses: actions/setup-node@v6
              with: 
                node-version: 20

            - name: print node js version
              run: node -v

            - name: Istall dependencies
              run: npm ci

            - name: run tests
              run: npm run test
